### ISSUE TITLE
Erro ao acessar sale.order

### ISSUE THREAD

**Issue by Mackilem** [Trust-Code/l10n-brazil#11]
File "/home/trustcode/odoo/odoo/openerp/models.py", line 5773, in _onchange_eval
    method_res = getattr(self._model, method)(*args)
TypeError: onchange_discount_rate() takes exactly 1 argument (5 given)

o erro está acontecendo ao acessar o formulário de cotações.

**Comment by danimaribeiro** [comment]
É necessário atualizar o módulo: l10n_br_sale
