### ISSUE TITLE
Fatura - Documento Relacionado

### ISSUE THREAD

**Issue by Mackilem** [Trust-Code/l10n-brazil#18]
Existem alguns tipos de notas fiscal, entre elas a de devolução que por lei é obrigatório preencher o campo "Documento Relacionado".

Hoje o recurso existe, porém pode ser automáticamente preenchido quando utilizado a rotina de reembolso de mercadoria.

att,

**Comment by Mackilem** [comment]
Através da NT2013/005 foi disponibilizada a nova finalidade de Emissão: 4=Devolução de mercadoria.

A nova finalidade de emissão da NF-e vem acompanhada de algumas regras de validação, entre elas:
- Para as NF-e de devolução de mercadoria, obrigatoriamente deverá ser informado o documento fiscal referenciado, que pode ser outra NF-e, uma Nota Fiscal Modelo 1, Nota Fiscal de Produtor Primário, etc.;

**Comment by danimaribeiro** [comment]
Implementado parcialmente.
