### ISSUE TITLE
Fatura - Finalidade da Emissão para Devoluções

### ISSUE THREAD

**Issue by Mackilem** [Trust-Code/l10n-brazil#19]
No formulário de fatura, é necessário a inclusão de uma nova opção no campo "Finalidade de Emissão": segue imagem da nota técnica:

![final_emissao](https://cloud.githubusercontent.com/assets/6154245/8134779/43661b0e-1108-11e5-96cf-12664bde2b7c.png)

**Comment by danimaribeiro** [comment]
Esperando publicação.
