### ISSUE TITLE
Fatura - Referência do Cliente nas Observações

### ISSUE THREAD

**Issue by Mackilem** [Trust-Code/l10n-brazil#20]
No formulário de fatura, o campo "Referência/Descrição" serve para anotar, por exemplo o numero da ordem de compra do cliente, ou alguma outra referência utilizada por ele.

Com isso, é necessário automatizar a criação de uma mensagem a ser impresso no complemento da Danfe, da seguinte forma:

OC / Referência do Cliente: "valor do campo"

att,

**Comment by danimaribeiro** [comment]
Adicionado ao xml por enquanto.
