### ISSUE TITLE
Fatura - Transferir o desconto para o preço unitário

### ISSUE THREAD

**Issue by Mackilem** [Trust-Code/l10n-brazil#22]
o que ta pegando:

A lei tributária no Brasil não permite isentar impostos quando concedido descontos na NFe, ou seja se o preço original era R$ 100,00 e for dado desconto de 10%.... para efeito de base de calculo dos impostos continuará sendo os original R$ 100 reais de base.

O que precisa ser melhorado na fatura é:

1 - Criar uma opção nas configurações/vendas para ativar o recurso, abaixo:
2 - Na geração automática da fatura, advinda do pedido, alterar o preço unitário de cada produto, inserindo o desconto no preço unitário do item.
3- Com o recurso ativado, o campo desconto na linha do produto na fatura fica em branco.

Obs.: No pedido é interessante que saia o desconto da forma como está hoje para que o cliente visualize bem o desconto.

att,

**Comment by danimaribeiro** [comment]
:+1:
