### ISSUE TITLE
O frete é subtraido do imposto e o seguro é acrescentado em outras despesas.

### ISSUE THREAD

**Issue by coemoraes** [Trust-Code/l10n-brazil#36]
Ola, Boa Noite!

Ao se criar um novo pedido de venda quando se acrescenta o frete ele é subtraido do imposto e o seguro somado em outras despesas, alguém ja observou este comportamento? Ja sabemos onde esta no código , gostaríamos de esclarecer a regra quanto a este campo, qual a finalidade do campo imposto? Esta correto este comportamento?

Obrigado.

**Comment by danimaribeiro** [comment]
Cheque este issue
https://github.com/odoo-brazil/l10n-brazil/issues/50

**Comment by danimaribeiro** [comment]
Conseguiu resolver o seu problema?

**Comment by coemoraes** [comment]
Ola. Boa tarde!!

Testamos a solução, mas parece não funcionou.

Obrigado.

Coe Moraes

**Comment by coemoraes** [comment]
Estranho realmente, testei de diversas formas, talvez tenha algo errado com nossa instalacao, mas percebemos que o commit https://github.com/odoo-brazil/l10n-brazil/pull/30/files provavelmente esta relacionado ao issue, ainda nao foi aprovado.
