### ISSUE TITLE
Erro ao gerar cotação apartir da oportinidade

### ISSUE THREAD

**Issue by Mackilem** [Trust-Code/l10n-brazil#54]
Movimentação não permitida!
Em função do controle multiempresa, não é permitido salvar cotações com empresas diferentes
(Partner, possuí empresa ITECH SOLUÇÕES que é diferente de False da cotação) 

Passos para reproduzir

Criar um propecto aonde o cliente não esteja cadastrado.
Transformar em oportunidade, gerando o cliente.
Na oportunidade gerar uma cotação.

**Comment by Mackilem** [comment]
Pelo que entendi, o problema é que o campo company_id tem um default relacionado com a empresa logada do usuário.... retirando o default o company_id para quando estivermos utilizando o modo multcompany... parece que resolve  o problema

**Comment by danimaribeiro** [comment]
Corrigido com configuração:

![configuracao](https://cloud.githubusercontent.com/assets/854781/13181361/eac53c00-d713-11e5-8ced-3f371457cf2e.png)
